// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: file.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :one
insert into files (file_name, file_type, file_size, key, url, relation_id, account_id)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
`

type CreateFileParams struct {
	FileName   string
	FileType   Filetype
	FileSize   int64
	Key        string
	Url        string
	RelationID sql.NullInt64
	AccountID  sql.NullInt64
}

func (q *Queries) CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.Key,
		arg.Url,
		arg.RelationID,
		arg.AccountID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
delete
from files
where id = $1
`

func (q *Queries) DeleteFileByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFileByID, id)
	return err
}

const getFileByRelationID = `-- name: GetFileByRelationID :many
select id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
from files
where relation_id = $1
`

func (q *Queries) GetFileByRelationID(ctx context.Context, relationID sql.NullInt64) ([]*File, error) {
	rows, err := q.db.Query(ctx, getFileByRelationID, relationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.Key,
			&i.Url,
			&i.RelationID,
			&i.AccountID,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByRelationIDIsNULL = `-- name: GetFileByRelationIDIsNULL :many
select id, key
from files
where relation_id is null and file_name != 'AccountAvatar'
`

type GetFileByRelationIDIsNULLRow struct {
	ID  int64
	Key string
}

func (q *Queries) GetFileByRelationIDIsNULL(ctx context.Context) ([]*GetFileByRelationIDIsNULLRow, error) {
	rows, err := q.db.Query(ctx, getFileByRelationIDIsNULL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFileByRelationIDIsNULLRow{}
	for rows.Next() {
		var i GetFileByRelationIDIsNULLRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileDetailsByID = `-- name: GetFileDetailsByID :one
select id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
from files
where id = $1
`

func (q *Queries) GetFileDetailsByID(ctx context.Context, id int64) (*File, error) {
	row := q.db.QueryRow(ctx, getFileDetailsByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const getFileKeyByID = `-- name: GetFileKeyByID :one
select key
from files
where id = $1
`

func (q *Queries) GetFileKeyByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getFileKeyByID, id)
	var key string
	err := row.Scan(&key)
	return key, err
}

const getGroupAvatar = `-- name: GetGroupAvatar :one
select id, file_name, file_type, file_size, key, url, relation_id, account_id, create_at
from files
where relation_id = $1
    and account_id is null
`

func (q *Queries) GetGroupAvatar(ctx context.Context, relationID sql.NullInt64) (*File, error) {
	row := q.db.QueryRow(ctx, getGroupAvatar, relationID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.Key,
		&i.Url,
		&i.RelationID,
		&i.AccountID,
		&i.CreateAt,
	)
	return &i, err
}

const updateGroupAvatar = `-- name: UpdateGroupAvatar :exec
update files
set url = $1
where relation_id = $2 and file_name = 'groupAvatar'
`

type UpdateGroupAvatarParams struct {
	Url        string
	RelationID sql.NullInt64
}

func (q *Queries) UpdateGroupAvatar(ctx context.Context, arg *UpdateGroupAvatarParams) error {
	_, err := q.db.Exec(ctx, updateGroupAvatar, arg.Url, arg.RelationID)
	return err
}
